name: Obituary Scraper Cron

on:
  schedule:
    # Runs every 1 hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  scrape-and-store:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Scraper
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd scraper
          python scraper.py
          
      - name: Trigger WordPress Publisher
        run: curl -X GET "https://apply.goodprofile.com.ng/wp-json/obituary/v1/fetch?secret=UcxYhQvpyn1w"
